language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0
    - android-22
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

dependencies:
  pre:
    - echo y | android update sdk --no-ui --all --filter "android-23"

test:
  override:
    - ./gradlew clean
    - ./gradlew android:assembleRelease

notifications:
  email: false